defaults:
  - _self_
  - data_cfg: icv_data
  - icv_module: icv_module
  - trainer: zero2
  - lmm: idefics-9B
  - prompt: ${lmm}_${data_cfg/task}

seed: 426

run_name: "debug"
model_cpk_dir: ${oc.env:MODEL_CPK_DIR}
model_name: "${lmm.model_name}"
device: "cpu"
# model_name: "HuggingFaceM4/tiny-random-idefics"

result_dir: ${oc.env:RESULT_DIR}


hydra:
  run:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${run_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
